# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_auto_20180101_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt_agency_access',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complain.Govt_Agency'),
        ),
    ]
